name: Shell Linting and Installation Check

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint_and_install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: ['bash', 'zsh', 'fish', 'csh', 'tcsh', 'ksh', 'dash']
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck fish csh tcsh ksh dash zsh

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install shellcheck fish zsh
        brew install --cask tcsh ksh

    - name: Run ShellCheck
      run: shellcheck bin/*.sh

    - name: Test Installation
      run: |
        chmod +x install.sh
        ./install.sh
        case "${{ matrix.shell }}" in
          'bash')  source ~/.bashrc  ;;
          'zsh')   source ~/.zshrc   ;;
          'fish')  source ~/.config/fish/config.fish ;;
          'csh')   source ~/.cshrc   ;;
          'tcsh')  source ~/.tcshrc  ;;
          'ksh')   source ~/.kshrc   ;;
          'dash')  source ~/.dashrc  ;; # If dash has an rc file
          *) echo "Shell not supported" ;;
        esac
        type bin/swtp
